### ISSUE TITLE
NONCE calculation seems off and causes dropped txs on-chain

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core-ethereum#102]
# Introduction
Whenever we start a payment channel, we are passing a nonce to the transaction. However, it seems we are reusing the payment-channel nonce alongside the account transaction nonce, making validators and blocks within the chain to drop the signed transaction. We need to ensure transactions have always a valid nonce to make sure they get picked by the chain validators.

# Task Description
- [x] Confirm the current value of a proposed transaction nonce does not always match the nonce needed by the account (i.e. uses the one from the payment channel contract)
- [x] Propose a fix where accounts always use they given nonce, and provide a better name to differentiate between the account tx nonces and the payment channel contract.

# Definition of complete
The task is considered completed when a specific name has been given to differentiate the smart contract nonce and the nonce used by the node, ensuring all transactions signed and broadcasted by the account are picked up and valid.

# Testing criteria
- [x] On start, accounts can always open a payment channel
