### ISSUE TITLE
On bootstrap, the connector writes the state of the account secret before reading and verifying it exists

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core-ethereum#103]
# Introduction
On the first check, the node submits the account secret to the payment channel contract, an expected behaviour. However, upon restarting the node, the node resubmits its already stored secret in the smart contract, which incurs in unnecessary costs. This behaviour repeats itself every time the node is started. The following [tx](https://blockscout.com/poa/xdai/tx/0x14a5e74172268aae757036827fd43ec7aa8e6e439b7c25f9c14bae4cc3307b19) is one of the bootstrap node, whereas this [tx](https://blockscout.com/poa/xdai/tx/0x3b8e6ef19b672c4dc4dbab2da70e7aab99886d9905260dc518f52936ae38dad3) is an example of the unnecessary follow-up one. We need to make sure only the first tx goes through, and no unnecessary transactions are made by the node.

# Task Description
- [ ] Review the `_submit` method from the connector to make sure we read the value of the secret submission state before trying to pushing the on-chain transaction.

# Definition of complete
The task is considered completed when the connector is able to read the account secret locally and no longer submits it unnecessarily on every node restart.

# Testing criteria
- [ ] The node is starting and an initial payment channel opening transaction is called.
- [ ] The node is restarted and no further transactions are sent to the payment-channel contract.
