### ISSUE TITLE
Upon a failed transaction, the connector fails to encode the ABI due extra bytes

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-core-ethereum#105]
# Introduction
After a node fails to register the account secret, the node enters a state where its off-chain (db) data does not matches the on-chain one (since the tx failed). So, after restarting the node, it will try to retrieve this data from the payment-channel, but fail to do so. This will return an encoding error generated in https://github.com/hoprnet/hopr-core-ethereum/blob/412b6cfdf6d8c31a28c4e5e07cf5c8289cced71b/src/utils/index.ts#L321-L322, mainly because the ABI to encode has `32 bytes`, the wrong length for processing the tx (as txs are stored using `27 bytes`). This can be seen by measuring the length of a given ABI (e.g. `0x488191d02e42c5da8f11d94f0c7af5350a1c97f733b9c1d1ce0b940442a4ad1e`, which has `66` (actually `64` removing `0x`) i.e. `32 bytes). 

# Task Description
- [ ] Provide a way to recover on failed transactions, either by detecting the failed state and/or preventing such state.
- [ ] Provide a better error description on encoding to showcase the mismatch nature of the tx which web3 fails to parse.

# Definition of complete
The bug is completely patched when upon a node has failed to register to our payment channel, we are able to recover gracefully either by resetting the node state and/or automatically detecting the issue and recovering.

# Testing criteria
- [ ] Upon a failed payment channel registering transaction, the node can recover and restart the tx.

# Notes
As this is a symptom of #102, to verify this one you might need to create a fake nonce to get to the state where you can replicate the bug (i.e. node started and stored secret but on-chain tx failed).
